### ISSUE TITLE
Status update on 2.0.0 final release?

### ISSUE THREAD

**Issue by marcortola** [VIPnytt/RobotsTxtParser#3]
Hi @JanPetterMG,

Maybe this is not the right place to ask for a status update about the 2.0.0 release, but perhaps there are more people interested in the same question. The fact is that v2 is more useful and more stable than v1, so I have finally decided to use it when the final release rolls out, but I can't do it with the composer "minimum-stability" set to "stable".

Just curious if you have any guess on when it might be released or a list of issues you still want to close before releasing, I can help in that case.

Thank you for the good job you have done developing this library!

**Comment by JanPetterMG** [comment]
Hi, I'm glad you asked.

I've been using the v2 draft for some time now, and there's some places with room for improvements. It's mainly all about the database integrations, witch needs a rewrite, but also some minor rendering optimizations.
There's some "inline" directives, I've not yet found a single reference to them... After removing support for those, bench marks is showing a mayor performance increase.

Most of the work is already done, currently I'm working on writing documentation. I'll post the updates as soon as that's done, likely within a day or two.

Expect the final release after an short testing period. I want it to be as bug-free as possible.

**Comment by JanPetterMG** [comment]
Changes committed.
There's one bug left, in PHP 7.2, when using MySQL for back end `crawl-delay` handling, the delay time returned might be less than it should. I'll have to take a look at that one tomorrow...

Anyway, builds for PHP 5.6->7.1 is currently passing, with 95% test coverage.

**Comment by marcortola** [comment]
I hope PR #4 solves the problem you issued in your last message.
Thanks you for notifying us about the release status. :grinning:

**Comment by JanPetterMG** [comment]
Great work 👍 

Release candidate 3 now released. If no more issues shows up, I'll release the final v2.0.0 stable on Sunday

**Comment by JanPetterMG** [comment]
[Version 2.0.0 stable](https://github.com/VIPnytt/RobotsTxtParser/releases/tag/v2.0.0) is finally released.
