### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by czepter** [VIPnytt/RobotsTxtParser#9]
Please update composer file to allow guzzlehttp > 7.2

Cheers & thanks

**Comment by czepter** [comment]
at first composer used "old" version 1.1
after upgrading to new v2 a php incompatibility was raised

please upgrade to php8 at least in composer

**Comment by JanPetterMG** [comment]
[Version 2.1.0](https://github.com/VIPnytt/RobotsTxtParser/releases/tag/v2.1.0) is now released, with PHP 8 support.
